apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: php
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets:
        - name: ghcr-login

      initContainers:
        - name: wait-for-deps
          image: plex-react:latest

          command: ["sh", "-c", "true"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: php
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets:
        - name: ghcr-login

      initContainers:
        - name: wait-for-deps
          image: plex-react:latest

          command: ["sh", "-c", "until curl -sf http://web/up; do echo 'Waiting for dependencies...'; sleep 2; done;"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: php
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      imagePullSecrets:
        - name: ghcr-login

      initContainers:
        - name: wait-for-deps
          image: plex-react:latest

          command: ["sh", "-c", "until curl -sf http://web/up; do echo 'Waiting for dependencies...'; sleep 2; done;"]
